name: torah_share
description: TorahShare Description

# Remove this line if you wish to publish to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.8.1+1
  cloud_firestore: ^2.3.0
  contacts_service: ^0.6.1
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  esys_flutter_share: ^1.0.2
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.2
  firebase_storage: ^9.0.0
  flutter_local_notifications: ^6.0.0
  font_awesome_flutter: ^9.0.0
  geocoding: ^2.0.0
  geolocator: ^7.0.3
  get: ^4.1.3
  google_sign_in: ^5.0.4
  image_picker: ^0.7.5+3
  lottie: ^1.0.1
  path_provider: ^1.1.0
  permission_handler: ^8.1.2
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  telephony: ^0.1.4
  timeago: ^3.1.0
  video_compress: ^3.0.0
  video_player: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/translations/
    - assets/images/
    - assets/icons/
    - assets/icons/application_icon.png
    - assets/icons/filled/
    - assets/icons/outlined/

  fonts:
    - family: NunitoSans-ExtraBold
      fonts:
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
    - family: NunitoSans-Bold
      fonts:
        - asset: assets/fonts/NunitoSans-Bold.ttf
    - family: NunitoSans-Light
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf
    - family: NunitoSans-Regular
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
    - family: NunitoSans-SemiBold
      fonts:
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
